Traceback (most recent call last):
  File "D:\projects\MyHome\HomeTether\HTCordinator.py", line 16, in <module>
    thread.start_new_thread(loop0, {})
TypeError: 2nd arg must be a tuple
